server:
  port: 8080

spring:
  datasource:
    driver-class-name:
    url: jdbc:mysql://127.0.0.1/groomProject?characterEncoding=utf-8
    username: root
    password: 7370
    
mybatis:
  mapper-locations: mapper/*Mapper.xml
  
